version: '3.4'
services:
  broken-api:
    build: .
    environment:
      BROKEN_API_HOST: 0.0.0.0
      BROKEN_API_PORT: 8000
      BROKEN_API_DATABASE_HOST: db
      BROKEN_API_DATABASE_NAME: brokendb
      BROKEN_API_DATABASE_USER: mysql_user
      BROKEN_API_DATABASE_PASSWORD: mysql_password
    ports:
      - "8000:8000"

  tests:
    build: tests/
    environment:
      BROKEN_API_HOST: broken-api
      BROKEN_API_PORT: 8000

  mysql:
    image: arm64v8/mysql:oracle
    hostname: db
    environment:
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_DATABASE: brokendb
      MYSQL_ROOT_PASSWORD: p4ssw0rd
    # ports:
    #   - "3306:3306" # uncomment to access from localhost
    volumes:
      - "./tests/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
